# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/rndusers/Vivek.Dixit/Dev/rigging/automation_system/rigg_v002.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 218)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.connection_layout = QtWidgets.QHBoxLayout()
        self.connection_layout.setObjectName("connection_layout")
        self.connection_label = QtWidgets.QLabel(self.centralwidget)
        self.connection_label.setObjectName("connection_label")
        self.connection_layout.addWidget(self.connection_label)
        self.connection_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.connection_combobox.setObjectName("connection_combobox")
        self.connection_layout.addWidget(self.connection_combobox)
        self.verticalLayout.addLayout(self.connection_layout)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mesh_btn = QtWidgets.QRadioButton(self.groupBox)
        self.mesh_btn.setObjectName("mesh_btn")
        self.horizontalLayout.addWidget(self.mesh_btn)
        self.cruve_btn = QtWidgets.QRadioButton(self.groupBox)
        self.cruve_btn.setObjectName("cruve_btn")
        self.horizontalLayout.addWidget(self.cruve_btn)
        self.ctrl_mesh_btn = QtWidgets.QRadioButton(self.groupBox)
        self.ctrl_mesh_btn.setObjectName("ctrl_mesh_btn")
        self.horizontalLayout.addWidget(self.ctrl_mesh_btn)
        self.verticalLayout.addWidget(self.groupBox)
        self.seprator = QtWidgets.QFrame(self.centralwidget)
        self.seprator.setFrameShape(QtWidgets.QFrame.HLine)
        self.seprator.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.seprator.setObjectName("seprator")
        self.verticalLayout.addWidget(self.seprator)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.poly_chkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.poly_chkbox.setObjectName("poly_chkbox")
        self.horizontalLayout_3.addWidget(self.poly_chkbox)
        self.surface_chkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.surface_chkbox.setObjectName("surface_chkbox")
        self.horizontalLayout_3.addWidget(self.surface_chkbox)
        self.combine_chkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.combine_chkbox.setObjectName("combine_chkbox")
        self.horizontalLayout_3.addWidget(self.combine_chkbox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.create_btn = QtWidgets.QPushButton(self.centralwidget)
        self.create_btn.setObjectName("create_btn")
        self.verticalLayout.addWidget(self.create_btn)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connection_label.setText(_translate("MainWindow", "Connection Type :"))
        self.groupBox.setTitle(_translate("MainWindow", "Create With"))
        self.mesh_btn.setText(_translate("MainWindow", "Mesh"))
        self.cruve_btn.setText(_translate("MainWindow", "Ctrl"))
        self.ctrl_mesh_btn.setText(_translate("MainWindow", "Ctrl + Mesh"))
        self.poly_chkbox.setText(_translate("MainWindow", "Polygon"))
        self.surface_chkbox.setText(_translate("MainWindow", "surfcae"))
        self.combine_chkbox.setText(_translate("MainWindow", "Combine"))
        self.create_btn.setText(_translate("MainWindow", "Create"))
