# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/vivek.dixit/pycharm/MayaDev/tools/rig_master/ui/uvPin_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_UVPinUi(object):
    def setupUi(self, UVPinUi):
        UVPinUi.setObjectName("UVPinUi")
        UVPinUi.resize(412, 507)
        self.centralwidget = QtWidgets.QWidget(UVPinUi)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.master_cluster_lbl = QtWidgets.QLabel(self.centralwidget)
        self.master_cluster_lbl.setObjectName("master_cluster_lbl")
        self.horizontalLayout.addWidget(self.master_cluster_lbl)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.master_cluster_listbox = QtWidgets.QListWidget(self.centralwidget)
        self.master_cluster_listbox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.master_cluster_listbox.setObjectName("master_cluster_listbox")
        self.verticalLayout.addWidget(self.master_cluster_listbox)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.uvpin_chkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.uvpin_chkbox.setObjectName("uvpin_chkbox")
        self.verticalLayout_2.addWidget(self.uvpin_chkbox)
        self.uvpin_listbox = QtWidgets.QListWidget(self.centralwidget)
        self.uvpin_listbox.setObjectName("uvpin_listbox")
        self.verticalLayout_2.addWidget(self.uvpin_listbox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.skin_cluster_chkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.skin_cluster_chkbox.setObjectName("skin_cluster_chkbox")
        self.verticalLayout_4.addWidget(self.skin_cluster_chkbox)
        self.skincluster_listbox = QtWidgets.QListWidget(self.centralwidget)
        self.skincluster_listbox.setObjectName("skincluster_listbox")
        self.verticalLayout_4.addWidget(self.skincluster_listbox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.remove_btn = QtWidgets.QPushButton(self.centralwidget)
        self.remove_btn.setObjectName("remove_btn")
        self.horizontalLayout_2.addWidget(self.remove_btn)
        self.add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout_2.addWidget(self.add_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.selected_vertex_listbox = QtWidgets.QListWidget(self.centralwidget)
        self.selected_vertex_listbox.setObjectName("selected_vertex_listbox")
        self.verticalLayout_3.addWidget(self.selected_vertex_listbox)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.create_btn = QtWidgets.QPushButton(self.centralwidget)
        self.create_btn.setObjectName("create_btn")
        self.verticalLayout_5.addWidget(self.create_btn)
        UVPinUi.setCentralWidget(self.centralwidget)

        self.retranslateUi(UVPinUi)
        QtCore.QMetaObject.connectSlotsByName(UVPinUi)

    def retranslateUi(self, UVPinUi):
        _translate = QtCore.QCoreApplication.translate
        UVPinUi.setWindowTitle(_translate("UVPinUi", "MainWindow"))
        self.master_cluster_lbl.setText(_translate("UVPinUi", "Master Cluster"))
        self.uvpin_chkbox.setText(_translate("UVPinUi", "Use Existing UV pin"))
        self.skin_cluster_chkbox.setText(_translate("UVPinUi", "Use Existing Skin Cluster"))
        self.label_2.setText(_translate("UVPinUi", "Points to create"))
        self.remove_btn.setText(_translate("UVPinUi", "-"))
        self.add_btn.setText(_translate("UVPinUi", "+"))
        self.create_btn.setText(_translate("UVPinUi", "Create"))
